<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MouseJiggler.Application\MouseJiggler.Application.csproj" />
  </ItemGroup>
</Project>
